# Generated by Django 5.2.1 on 2025-06-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
